"""Add 3R classification columns

Revision ID: 18faded1fb43
Revises: 20260923_add_cluster_name
Create Date: 2026-09-24 00:40:30.654912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18faded1fb43'
down_revision: Union[str, Sequence[str], None] = '20260923_add_cluster_name'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('three_r_category', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('three_r_category', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('semantic_match_cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incidents_three_r_category'), 'incidents', ['three_r_category'], unique=False)
    op.add_column('processing_jobs', sa.Column('total_runners', sa.Integer(), nullable=True))
    op.add_column('processing_jobs', sa.Column('total_repeaters', sa.Integer(), nullable=True))
    op.add_column('processing_jobs', sa.Column('total_rares', sa.Integer(), nullable=True))
    op.alter_column('processing_jobs', 'progress_stage',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_jobs', 'progress_stage',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('processing_jobs', 'total_rares')
    op.drop_column('processing_jobs', 'total_repeaters')
    op.drop_column('processing_jobs', 'total_runners')
    op.drop_index(op.f('ix_incidents_three_r_category'), table_name='incidents')
    op.drop_column('incidents', 'semantic_match_cluster_id')
    op.drop_column('incidents', 'three_r_category')
    op.drop_column('clusters', 'three_r_category')
    # ### end Alembic commands ###
