"""increase_priority_size

Revision ID: 1adb0c3011ff
Revises: 7962df5f612c
Create Date: 2026-09-29 09:51:01.277161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1adb0c3011ff'
down_revision: Union[str, Sequence[str], None] = '7962df5f612c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_incidents_assignment_group'), 'incidents', ['assignment_group'], unique=False)
    op.create_index(op.f('ix_incidents_cluster_id'), 'incidents', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_incidents_configuration_item'), 'incidents', ['configuration_item'], unique=False)
    op.drop_column('processing_jobs', 'filter_ast')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('filter_ast', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_incidents_configuration_item'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_cluster_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assignment_group'), table_name='incidents')
    op.alter_column('incidents', 'priority',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
