"""Add filter_ast to ProcessingJob

Revision ID: 7962df5f612c
Revises: 80a7d13b10c8
Create Date: 2026-09-28 19:14:53.569358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7962df5f612c'
down_revision: Union[str, Sequence[str], None] = '80a7d13b10c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('filter_ast', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'filter_ast')
    # ### end Alembic commands ###
