"""Add job_type and AI cluster fields

Revision ID: f9e4f7366423
Revises: 1adb0c3011ff
Create Date: 2026-10-05 02:06:54.778206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e4f7366423'
down_revision: Union[str, Sequence[str], None] = '1adb0c3011ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('ai_cluster_name', sa.String(length=300), nullable=True))
    op.add_column('clusters', sa.Column('naming_status', sa.String(length=20), server_default='STANDARD', nullable=False))
    op.add_column('processing_jobs', sa.Column('job_type', sa.String(length=30), server_default='PROCESSING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'job_type')
    op.drop_column('clusters', 'naming_status')
    op.drop_column('clusters', 'ai_cluster_name')
    # ### end Alembic commands ###
